rpc:
  endpoint: "http://63.32.188.217:18545"
ethereum:
  checkpoint: #block to start listening for deposits from
  confirmations: 20 #number of confirmations to wait for
horizon:
  endpoint: "http://localhost:18080"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4" # Issuer of assets
log:
  level: info
  disable_sentry: true
deposit:
  admin_signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
funnel:
  gas_price: "1"
  threshold: "1"
  hot_wallet: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  private_key: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"
deployer:
  private_key: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"
  gas_price: "20"
  gas_limit: "1200000"
  contract_owner: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  contract_count: 1

